[package]
name = "dol-entity-internal"
version.workspace = true
edition.workspace = true
publish = false
description = "DOL Entity, Field, FieldType, and Schema (internal, uses dol-expr)"

[dependencies]
dol-expr = { path = "../dol-expr" }
serde    = { workspace = true, optional = true }

[features]
default = []
serde = ["dep:serde", "dol-expr/serde"]
