[package]
name = "dol-stream"
version.workspace = true
edition.workspace = true
publish = false
description = "DOL stream/time-series/IoT IR data types"
readme = "README.md"

[dependencies]
dol-core = { workspace = true }
dol-expr = { workspace = true }
serde = { workspace = true, optional = true }

[features]
default = []
std = ["dol-core/std", "dol-expr/std"]
serde = ["dep:serde", "dol-core/serde", "dol-expr/serde"]

[lints]
workspace = true
