//! Migration planning — direction detection and step ordering.

use super::registry::AppliedMigration;
use super::{Migration, MigrationError, MigrationStep};

// ===========================================================================
// Direction & Target
// ===========================================================================

/// The direction of a migration plan.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum MigrationDirection {
    /// Apply migrations forward (run `up()` steps).
    Forward,
    /// Roll back migrations (run `down()` steps).
    Backward,
}

/// The target state for a migration plan.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum MigrationTarget {
    /// Apply all pending migrations (migrate to latest).
    Latest,
    /// Migrate to a specific version (forward or backward as needed).
    Version(String),
    /// Roll back the last N applied migrations.
    Rollback(usize),
    /// Roll back all applied migrations (empty database).
    Reset,
}

// ===========================================================================
// Planned step — a single step in a migration plan
// ===========================================================================

/// A step in a migration plan, annotated with direction and version metadata.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct PlannedStep {
    /// The migration version this step belongs to.
    pub version: String,
    /// The migration description.
    pub description: String,
    /// The direction (forward or backward).
    pub direction: MigrationDirection,
    /// The actual migration steps to execute.
    pub steps: Vec<MigrationStep>,
    /// The checksum of the migration for validation.
    pub checksum: String,
}

// ===========================================================================
// MigrationPlan — an ordered list of planned steps
// ===========================================================================

/// An ordered plan of migration steps to execute.
///
/// Plans are generated by [`MigrationRunner::plan`] and can be:
/// - Inspected (dry-run) via [`MigrationPlan::steps`]
/// - Rendered to SQL/KV/Storage output via [`MigrationRunner::render_plan`]
/// - Applied by iterating over steps and executing against a backend
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct MigrationPlan {
    planned_steps: Vec<PlannedStep>,
}

impl MigrationPlan {
    /// Create a plan from a list of planned steps.
    pub(crate) fn from_steps(steps: Vec<PlannedStep>) -> Self {
        Self {
            planned_steps: steps,
        }
    }

    /// Returns the ordered steps in this plan.
    pub fn steps(&self) -> &[PlannedStep] {
        &self.planned_steps
    }

    /// Returns the number of steps in this plan.
    pub fn len(&self) -> usize {
        self.planned_steps.len()
    }

    /// Returns true if the plan has no steps (database is up to date).
    pub fn is_empty(&self) -> bool {
        self.planned_steps.is_empty()
    }

    /// Returns the overall direction of this plan.
    ///
    /// Returns `None` if the plan is empty.
    pub fn direction(&self) -> Option<MigrationDirection> {
        self.planned_steps.first().map(|s| s.direction)
    }
}

// ===========================================================================
// Plan generation logic
// ===========================================================================

/// Compute a checksum for a list of migration steps.
///
/// Uses the `Debug` representation of steps hashed with [`std::hash::DefaultHasher`].
/// This is a **change-detection** checksum, not a cryptographic hash. It is
/// deterministic within a single Rust compiler version but may vary across
/// major Rust versions if `Debug` formatting or `DefaultHasher` internals
/// change. When that happens, re-applying migrations will update the stored
/// checksums. For cross-version stability, callers can provide their own
/// checksum via the [`MigrationRegistry`] when marking migrations as applied.
pub(crate) fn compute_checksum(steps: &[MigrationStep]) -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let mut hasher = DefaultHasher::new();
    format!("{:?}", steps).hash(&mut hasher);
    format!("{:016x}", hasher.finish())
}

/// Plan a forward migration to the latest version.
pub(crate) fn plan_forward(
    migrations: &[Box<dyn Migration>],
    applied: &[AppliedMigration],
) -> Result<MigrationPlan, MigrationError> {
    let applied_versions: std::collections::HashSet<&str> =
        applied.iter().map(|a| a.version.as_str()).collect();

    let mut steps = Vec::new();
    for migration in migrations {
        if !applied_versions.contains(migration.version()) {
            let up_steps = migration.up();
            let checksum = compute_checksum(&up_steps);
            steps.push(PlannedStep {
                version: migration.version().to_string(),
                description: migration.description().to_string(),
                direction: MigrationDirection::Forward,
                steps: up_steps,
                checksum,
            });
        }
    }

    Ok(MigrationPlan::from_steps(steps))
}

/// Plan a migration to a specific target.
pub(crate) fn plan_to_target(
    migrations: &[Box<dyn Migration>],
    applied: &[AppliedMigration],
    target: &MigrationTarget,
) -> Result<MigrationPlan, MigrationError> {
    match target {
        MigrationTarget::Latest => plan_forward(migrations, applied),

        MigrationTarget::Version(target_version) => {
            // Validate target exists
            if !migrations.iter().any(|m| m.version() == target_version) {
                return Err(MigrationError::TargetNotFound(target_version.clone()));
            }

            let applied_versions: std::collections::HashSet<&str> =
                applied.iter().map(|a| a.version.as_str()).collect();

            let target_idx = migrations
                .iter()
                .position(|m| m.version() == target_version)
                .unwrap();

            let mut steps = Vec::new();

            // Forward: apply unapplied migrations up to and including target
            for migration in &migrations[..=target_idx] {
                if !applied_versions.contains(migration.version()) {
                    let up_steps = migration.up();
                    let checksum = compute_checksum(&up_steps);
                    steps.push(PlannedStep {
                        version: migration.version().to_string(),
                        description: migration.description().to_string(),
                        direction: MigrationDirection::Forward,
                        steps: up_steps,
                        checksum,
                    });
                }
            }

            // Backward: revert applied migrations after target (in reverse order)
            for migration in migrations[target_idx + 1..].iter().rev() {
                if applied_versions.contains(migration.version()) {
                    let down_steps = migration.down();
                    let checksum = compute_checksum(&migration.up());
                    steps.push(PlannedStep {
                        version: migration.version().to_string(),
                        description: migration.description().to_string(),
                        direction: MigrationDirection::Backward,
                        steps: down_steps,
                        checksum,
                    });
                }
            }

            Ok(MigrationPlan::from_steps(steps))
        }

        MigrationTarget::Rollback(n) => {
            // Roll back the last N applied migrations (in reverse applied order)
            let mut to_revert: Vec<&AppliedMigration> = applied.iter().collect();
            to_revert.sort_by(|a, b| b.version.cmp(&a.version));
            to_revert.truncate(*n);

            let mut steps = Vec::new();
            for applied_migration in to_revert {
                if let Some(migration) = migrations
                    .iter()
                    .find(|m| m.version() == applied_migration.version)
                {
                    let down_steps = migration.down();
                    let checksum = compute_checksum(&migration.up());
                    steps.push(PlannedStep {
                        version: migration.version().to_string(),
                        description: migration.description().to_string(),
                        direction: MigrationDirection::Backward,
                        steps: down_steps,
                        checksum,
                    });
                }
            }

            Ok(MigrationPlan::from_steps(steps))
        }

        MigrationTarget::Reset => {
            // Roll back all applied migrations in reverse order
            let mut to_revert: Vec<&AppliedMigration> = applied.iter().collect();
            to_revert.sort_by(|a, b| b.version.cmp(&a.version));

            let mut steps = Vec::new();
            for applied_migration in to_revert {
                if let Some(migration) = migrations
                    .iter()
                    .find(|m| m.version() == applied_migration.version)
                {
                    let down_steps = migration.down();
                    let checksum = compute_checksum(&migration.up());
                    steps.push(PlannedStep {
                        version: migration.version().to_string(),
                        description: migration.description().to_string(),
                        direction: MigrationDirection::Backward,
                        steps: down_steps,
                        checksum,
                    });
                }
            }

            Ok(MigrationPlan::from_steps(steps))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_helpers::{AddEmailIndex, CreateSessionsTable, CreateUsersTable};

    #[test]
    fn plan_forward_all_pending() {
        let migrations: Vec<Box<dyn Migration>> = vec![
            Box::new(CreateUsersTable),
            Box::new(AddEmailIndex),
            Box::new(CreateSessionsTable),
        ];
        let applied: Vec<AppliedMigration> = vec![];
        let plan = plan_forward(&migrations, &applied).unwrap();
        assert_eq!(plan.len(), 3);
        assert_eq!(plan.steps()[0].version, "20240101_000001");
        assert_eq!(plan.steps()[1].version, "20240102_000001");
        assert_eq!(plan.steps()[2].version, "20240103_000001");
    }

    #[test]
    fn plan_forward_partial() {
        let migrations: Vec<Box<dyn Migration>> = vec![
            Box::new(CreateUsersTable),
            Box::new(AddEmailIndex),
            Box::new(CreateSessionsTable),
        ];
        let applied = vec![AppliedMigration {
            version: "20240101_000001".into(),
            description: "Create users table".into(),
            checksum: "abc".into(),
            applied_at: None,
            execution_time_ms: None,
        }];
        let plan = plan_forward(&migrations, &applied).unwrap();
        assert_eq!(plan.len(), 2);
        assert_eq!(plan.steps()[0].version, "20240102_000001");
        assert_eq!(plan.steps()[1].version, "20240103_000001");
    }

    #[test]
    fn plan_forward_none_pending() {
        let migrations: Vec<Box<dyn Migration>> = vec![Box::new(CreateUsersTable)];
        let applied = vec![AppliedMigration {
            version: "20240101_000001".into(),
            description: "".into(),
            checksum: "".into(),
            applied_at: None,
            execution_time_ms: None,
        }];
        let plan = plan_forward(&migrations, &applied).unwrap();
        assert!(plan.is_empty());
    }

    #[test]
    fn plan_to_specific_version() {
        let migrations: Vec<Box<dyn Migration>> = vec![
            Box::new(CreateUsersTable),
            Box::new(AddEmailIndex),
            Box::new(CreateSessionsTable),
        ];
        let applied: Vec<AppliedMigration> = vec![];
        let plan = plan_to_target(
            &migrations,
            &applied,
            &MigrationTarget::Version("20240102_000001".into()),
        )
        .unwrap();
        assert_eq!(plan.len(), 2);
        assert_eq!(plan.steps()[0].version, "20240101_000001");
        assert_eq!(plan.steps()[1].version, "20240102_000001");
    }

    #[test]
    fn plan_rollback_n() {
        let migrations: Vec<Box<dyn Migration>> = vec![
            Box::new(CreateUsersTable),
            Box::new(AddEmailIndex),
            Box::new(CreateSessionsTable),
        ];
        let applied = vec![
            AppliedMigration {
                version: "20240101_000001".into(),
                description: "".into(),
                checksum: "".into(),
                applied_at: None,
                execution_time_ms: None,
            },
            AppliedMigration {
                version: "20240102_000001".into(),
                description: "".into(),
                checksum: "".into(),
                applied_at: None,
                execution_time_ms: None,
            },
            AppliedMigration {
                version: "20240103_000001".into(),
                description: "".into(),
                checksum: "".into(),
                applied_at: None,
                execution_time_ms: None,
            },
        ];
        let plan = plan_to_target(&migrations, &applied, &MigrationTarget::Rollback(2)).unwrap();
        assert_eq!(plan.len(), 2);
        assert_eq!(plan.direction(), Some(MigrationDirection::Backward));
        assert_eq!(plan.steps()[0].version, "20240103_000001");
        assert_eq!(plan.steps()[1].version, "20240102_000001");
    }

    #[test]
    fn plan_reset() {
        let migrations: Vec<Box<dyn Migration>> =
            vec![Box::new(CreateUsersTable), Box::new(AddEmailIndex)];
        let applied = vec![
            AppliedMigration {
                version: "20240101_000001".into(),
                description: "".into(),
                checksum: "".into(),
                applied_at: None,
                execution_time_ms: None,
            },
            AppliedMigration {
                version: "20240102_000001".into(),
                description: "".into(),
                checksum: "".into(),
                applied_at: None,
                execution_time_ms: None,
            },
        ];
        let plan = plan_to_target(&migrations, &applied, &MigrationTarget::Reset).unwrap();
        assert_eq!(plan.len(), 2);
        // Reversed order
        assert_eq!(plan.steps()[0].version, "20240102_000001");
        assert_eq!(plan.steps()[1].version, "20240101_000001");
    }

    #[test]
    fn plan_target_not_found() {
        let migrations: Vec<Box<dyn Migration>> = vec![Box::new(CreateUsersTable)];
        let applied: Vec<AppliedMigration> = vec![];
        let result = plan_to_target(
            &migrations,
            &applied,
            &MigrationTarget::Version("nonexistent".into()),
        );
        assert!(matches!(result, Err(MigrationError::TargetNotFound(_))));
    }

    #[test]
    fn checksum_deterministic() {
        let steps = CreateUsersTable.up();
        let c1 = compute_checksum(&steps);
        let c2 = compute_checksum(&steps);
        assert_eq!(c1, c2);
        assert_eq!(c1.len(), 16); // 16 hex chars
    }

    #[test]
    fn checksum_different_for_different_steps() {
        let c1 = compute_checksum(&CreateUsersTable.up());
        let c2 = compute_checksum(&AddEmailIndex.up());
        assert_ne!(c1, c2);
    }
}
